const foodData = [
  {
    id: 1,
    title: "Cheese Burger",
    price: 149,
    description: "Juicy grilled burger with cheese and fresh veggies",
    category: "Burger",
    rating: 4.5,
    stock: 20,
    thumbnail:
      "https://assets.epicurious.com/photos/5c745a108918ee7ab68daf79/1:1/w_2560%2Cc_limit/Smashburger-recipe-120219.jpg",
  },
  {
    id: 2,
    title: "Margherita Pizza",
    price: 299,
    description: "Classic pizza with tomato sauce and mozzarella",
    category: "Pizza",
    rating: 4.7,
    stock: 15,
    thumbnail:
      "https://safrescobaldistatic.blob.core.windows.net/media/2022/11/PIZZA-MARGHERITA.jpg",
  },
  {
    id: 3,
    title: "Chicken Biryani",
    price: 249,
    description: "Aromatic basmati rice with spicy chicken",
    category: "Indian",
    rating: 4.8,
    stock: 10,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPcdlgGqTXb-qtbAK_WgscTy2TimgPjzn9fw&s",
  },
  {
    id: 4,
    title: "Veg Sandwich",
    price: 99,
    description: "Healthy sandwich with fresh vegetables",
    category: "Snacks",
    rating: 4.2,
    stock: 25,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNG6YHlYs-4zSLpSCWlfWbRNLVBEPemX7PTw&s",
  },
  {
    id: 5,
    title: "Pasta Alfredo",
    price: 199,
    description: "Creamy white sauce pasta with herbs",
    category: "Italian",
    rating: 4.6,
    stock: 12,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjfR7rd7Y5pg_G1j20uv4YqhsRITum4Lqt-g&s",
  },
  {
    id: 6,
    title: "Pepperoni Pizza",
    price: 349,
    description: "Loaded pizza with pepperoni and cheese",
    category: "Pizza",
    rating: 4.6,
    stock: 14,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQugXpVRngY9P616NZ57jyx2kl-Xoq_DbC58A&s",
  },
  {
    id: 7,
    title: "Paneer Tikka",
    price: 199,
    description: "Grilled paneer cubes with spices",
    category: "Indian",
    rating: 4.5,
    stock: 18,
    thumbnail:
      "https://lentillovingfamily.com/wp-content/uploads/2025/08/paneer-tikka-2.jpg",
  },
  {
    id: 8,
    title: "French Fries",
    price: 89,
    description: "Crispy golden fries with seasoning",
    category: "Snacks",
    rating: 4.3,
    stock: 30,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSuOc9gqFksrS2Q33Gqi2t_F5Niht1SUvHfg&s",
  },
  {
    id: 9,
    title: "Chicken Wrap",
    price: 159,
    description: "Soft wrap filled with spicy chicken",
    category: "Snacks",
    rating: 4.4,
    stock: 20,
    thumbnail:
      "https://valentinascorner.com/wp-content/uploads/2023/06/Chicken-Wrap-Recipe-4.jpg",
  },
  {
    id: 10,
    title: "Veg Fried Rice",
    price: 179,
    description: "Stir-fried rice with vegetables",
    category: "Chinese",
    rating: 4.3,
    stock: 16,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAU8YHg3EIZTWSI--YCNwJv80EjTIir1lI9Q&s",
  },

  {
    id: 11,
    title: "Chicken Noodles",
    price: 199,
    description: "Spicy noodles with chicken chunks",
    category: "Chinese",
    rating: 4.5,
    stock: 15,
    thumbnail:
      "https://i.ytimg.com/vi/MhzBUy-JOCE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBHrjt0krn7AlWVFHVR222EZTfRQg",
  },
  {
    id: 12,
    title: "Masala Dosa",
    price: 129,
    description: "Crispy dosa with potato filling",
    category: "South Indian",
    rating: 4.7,
    stock: 22,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRKEoKRezBKpHWYUIbZaKX9Kw_qCv-hQfTVw&s",
  },
  {
    id: 13,
    title: "Idli Sambar",
    price: 99,
    description: "Soft idli served with sambar",
    category: "South Indian",
    rating: 4.4,
    stock: 25,
    thumbnail:
      "https://shwetainthekitchen.com/wp-content/uploads/2022/01/Idli-Sambar.jpg",
  },
  {
    id: 14,
    title: "Chole Bhature",
    price: 149,
    description: "Spicy chickpeas with fried bread",
    category: "Indian",
    rating: 4.6,
    stock: 18,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnv8nOd0cc9Nemr_y1JLV41wTUUBg3vYAq2w&s",
  },
  {
    id: 15,
    title: "Rajma Chawal",
    price: 139,
    description: "Kidney beans curry with rice",
    category: "Indian",
    rating: 4.5,
    stock: 20,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrZZYV9Eu13fxu8qXT98ovX6SrG3hGOtpqPw&s",
  },

  {
    id: 16,
    title: "Chocolate Cake",
    price: 199,
    description: "Rich chocolate layered cake",
    category: "Dessert",
    rating: 4.8,
    stock: 10,
    thumbnail:
      "https://stephaniessweets.com/wp-content/uploads/2025/05/IMG_7203.jpg",
  },
  {
    id: 17,
    title: "Ice Cream Sundae",
    price: 149,
    description: "Ice cream with chocolate syrup",
    category: "Dessert",
    rating: 4.7,
    stock: 15,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmoMj74C2e5v3q-zRoGhqf-W2gCiKsktQlKA&s",
  },
  {
    id: 18,
    title: "Momos",
    price: 129,
    description: "Steamed dumplings with chutney",
    category: "Snacks",
    rating: 4.6,
    stock: 22,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_aUnJ8rHX-UnXNHCYnJa67Kb_OtkPbZeS7w&s",
  },
  {
    id: 19,
    title: "Spring Rolls",
    price: 139,
    description: "Crispy rolls with veggie filling",
    category: "Chinese",
    rating: 4.4,
    stock: 17,
    thumbnail:
      "https://hot-thai-kitchen.com/wp-content/uploads/2014/10/crispy-spring-rolls-sq-new.jpg",
  },
  {
    id: 20,
    title: "Grilled Chicken",
    price: 299,
    description: "Juicy grilled chicken with herbs",
    category: "Non-Veg",
    rating: 4.7,
    stock: 12,
    thumbnail:
      "https://www.budgetbytes.com/wp-content/uploads/2024/06/Grilled-Chicken-Overhead-500x500.jpg",
  },

  {
    id: 21,
    title: "Fish Curry",
    price: 249,
    description: "Spicy fish curry with rice",
    category: "Indian",
    rating: 4.5,
    stock: 10,
    thumbnail:
      "https://vismaifood.com/storage/app/uploads/public/daa/96d/7bc/thumb__1200_0_0_0_auto.jpg",
  },
  {
    id: 22,
    title: "Egg Curry",
    price: 179,
    description: "Boiled eggs in spicy gravy",
    category: "Indian",
    rating: 4.4,
    stock: 15,
    thumbnail:
      "https://www.whiskaffair.com/wp-content/uploads/2019/03/Chettinad-Egg-Curry-2-3.jpg",
  },
  {
    id: 23,
    title: "Tandoori Chicken",
    price: 349,
    description: "Roasted chicken with spices",
    category: "Indian",
    rating: 4.8,
    stock: 8,
    thumbnail:
      "https://static01.nyt.com/images/2024/05/16/multimedia/fs-tandoori-chicken-hmjq/fs-tandoori-chicken-hmjq-mediumSquareAt3X.jpg",
  },
  {
    id: 24,
    title: "Veg Pizza",
    price: 279,
    description: "Pizza loaded with vegetables",
    category: "Pizza",
    rating: 4.5,
    stock: 14,
    thumbnail:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2015/10/pizza-recipe-1.jpg",
  },
  {
    id: 25,
    title: "Cold Coffee",
    price: 119,
    description: "Chilled coffee with ice cream",
    category: "Beverage",
    rating: 4.6,
    stock: 20,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRVRoBguuadtGe6y5fvz_Mw9WP9Bc-Q_1Irg&s",
  },
  {
    id: 26,
    title: "Lassi",
    price: 89,
    description: "Sweet yogurt drink",
    category: "Beverage",
    rating: 4.5,
    stock: 25,
    thumbnail:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/lassi-recipe.jpg",
  },
  {
    id: 27,
    title: "Green Salad",
    price: 99,
    description: "Fresh healthy vegetable salad",
    category: "Healthy",
    rating: 4.3,
    stock: 30,
    thumbnail:
      "https://www.cubesnjuliennes.com/wp-content/uploads/2022/02/Mixed-Green-Salad-Recipe.jpg",
  },
  {
    id: 28,
    title: "Omelette",
    price: 79,
    description: "Fluffy egg omelette",
    category: "Breakfast",
    rating: 4.2,
    stock: 20,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTbnh5a6QOXaIR6FTPQ_XkvuwmZbwvTmuiqQ&s",
  },
  {
    id: 29,
    title: "Pancakes",
    price: 149,
    description: "Soft pancakes with syrup",
    category: "Breakfast",
    rating: 4.6,
    stock: 18,
    thumbnail:
      "https://www.tasteofhome.com/wp-content/uploads/2024/09/Buttermilk-Pancakes-TOHVP24_33639_MF_08_15_1.jpg",
  },
  {
    id: 30,
    title: "Waffles",
    price: 169,
    description: "Crispy waffles with toppings",
    category: "Dessert",
    rating: 4.7,
    stock: 15,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_er_GzjpqAA73WQgcAC9RKam6tRo1JYcAXw&s",
  },

  {
    id: 31,
    title: "Hot Dog",
    price: 129,
    description: "Sausage in bun with sauces",
    category: "Snacks",
    rating: 4.3,
    stock: 20,
    thumbnail:
      "https://www.belbrandsfoodservice.com/wp-content/uploads/2018/05/recipe-desktop-merkts-cheesy-hot-dawg.jpg",
  },
  {
    id: 32,
    title: "Nachos",
    price: 139,
    description: "Crunchy nachos with cheese dip",
    category: "Snacks",
    rating: 4.4,
    stock: 18,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6ui4fvm7xt0Z30qeSjF9ZnSSxjfgpcMCWew&s",
  },
  {
    id: 33,
    title: "Sushi",
    price: 399,
    description: "Japanese sushi rolls",
    category: "Japanese",
    rating: 4.7,
    stock: 10,
    thumbnail:
      "https://img-cdn.publive.online/fit-in/1200x675/filters:format(webp)/sanjeev-kapoor/media/media_files/2025/08/05/fried-sushi-yt-2025-08-05-11-37-18.jpg",
  },
  {
    id: 34,
    title: "Ramen",
    price: 299,
    description: "Hot ramen noodles with broth",
    category: "Japanese",
    rating: 4.6,
    stock: 12,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtiNQUr4Dtvnzl6uY6U1Zm9u5-fTHIIpT_Zw&s",
  },
  {
    id: 35,
    title: "Falafel",
    price: 179,
    description: "Crispy chickpea balls",
    category: "Middle Eastern",
    rating: 4.5,
    stock: 15,
    thumbnail:
      "https://www.yummytummyaarthi.com/wp-content/uploads/2022/07/falafel-1.jpeg",
  },

  {
    id: 36,
    title: "Shawarma",
    price: 199,
    description: "Wrap with grilled meat",
    category: "Middle Eastern",
    rating: 4.6,
    stock: 18,
    thumbnail:
      "https://pekis.net/sites/default/files/styles/social_share_1200/public/2025-04/Shawarma.webp?itok=TeUFSs0R",
  },
  {
    id: 37,
    title: "Brownie",
    price: 129,
    description: "Chocolate brownie dessert",
    category: "Dessert",
    rating: 4.8,
    stock: 14,
    thumbnail:
      "https://recipesblob.oetker.in/assets/9a89b75f976642dcab8ae407e2f4344e/1272x764/chocolate-brownie.webp",
  },
  {
    id: 38,
    title: "Cupcake",
    price: 99,
    description: "Soft cupcake with frosting",
    category: "Dessert",
    rating: 4.5,
    stock: 20,
    thumbnail:
      "https://www.preciouscore.com/wp-content/uploads/2025/07/ChocolateCupcakeswithchocolatefrosting_Feature_4.jpg",
  },
  {
    id: 39,
    title: "Milkshake",
    price: 149,
    description: "Thick creamy milkshake",
    category: "Beverage",
    rating: 4.7,
    stock: 18,
    thumbnail:
      "https://assets.epicurious.com/photos/647df8cad9749492c4d5d407/1:1/w_4506,h_4506,c_limit/StrawberryMilkshake_RECIPE_053123_3599.jpg",
  },
  {
    id: 40,
    title: "Smoothie",
    price: 139,
    description: "Healthy fruit smoothie",
    category: "Beverage",
    rating: 4.6,
    stock: 20,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvoAJ9JJCrw_XRVk0u0ADYNAt8hw5PiqCIYg&s",
  },

  {
    id: 41,
    title: "Avocado Toast",
    price: 179,
    description: "Toasted bread with avocado",
    category: "Healthy",
    rating: 4.5,
    stock: 15,
    thumbnail:
      "https://www.allrecipes.com/thmb/8NccFzsaq0_OZPDKmf7Yee-aG78=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AvocadoToastwithEggFranceC4x3-bb87e3bbf1944657b7db35f1383fabdb.jpg",
  },
  {
    id: 42,
    title: "Quinoa Bowl",
    price: 199,
    description: "Healthy quinoa meal bowl",
    category: "Healthy",
    rating: 4.4,
    stock: 12,
    thumbnail:
      "https://simplyhomecooked.com/wp-content/uploads/2023/04/quinoa-shrimp-bowl-18.jpg",
  },
  {
    id: 43,
    title: "Steak",
    price: 499,
    description: "Juicy grilled steak",
    category: "Non-Veg",
    rating: 4.8,
    stock: 8,
    thumbnail:
      "https://hips.hearstapps.com/hmg-prod/images/how-to-cook-steak-in-the-oven-index-66a3eda7b9f52.jpg?crop=0.6669164481079056xw:1xh;center,top&resize=1200:*",
  },
  {
    id: 44,
    title: "BBQ Ribs",
    price: 399,
    description: "Smoky BBQ ribs",
    category: "Non-Veg",
    rating: 4.7,
    stock: 10,
    thumbnail:
      "https://www.marthastewart.com/thmb/GL2chyMKQYGrNCVelNPJoh0J1Ck=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/MS-318389-oven-roasted-ribs-with-barbecue-sauce-hero-3x2-26714-f4b156a93dd44990b38fa7c6e6ef8c78.jpg",
  },
  {
    id: 45,
    title: "Garlic Bread",
    price: 129,
    description: "Toasted bread with garlic butter",
    category: "Italian",
    rating: 4.5,
    stock: 20,
    thumbnail:
      "https://static01.nyt.com/images/2018/12/11/dining/as-garlic-bread/as-garlic-bread-googleFourByThree-v2.jpg",
  },
  {
    id: 46,
    title: "Mac & Cheese",
    price: 199,
    description: "Cheesy pasta dish",
    category: "Italian",
    rating: 4.6,
    stock: 15,
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYs6EDBMfh_87XxxtAiVOXsdzBWjZLaiqn5Q&s",
  },
  {
    id: 47,
    title: "Chicken Wings",
    price: 249,
    description: "Spicy fried chicken wings",
    category: "Snacks",
    rating: 4.7,
    stock: 18,
    thumbnail:
      "https://sandersonfarms.com/wp-content/uploads/2017/04/Easy-Baked-chicken-Wings_20033_1-Thumbnail.jpg",
  },
  {
    id: 48,
    title: "Popcorn",
    price: 79,
    description: "Buttery popcorn snack",
    category: "Snacks",
    rating: 4.2,
    stock: 30,
    thumbnail:
      "https://www.simplyrecipes.com/thmb/Xzggu-Md45HKhhYSw4DK8tGlZ_I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Perfect-Popcorn-LEAD-41-4a75a18443ae45aa96053f30a3ed0a6b.JPG",
  },
  {
    id: 49,
    title: "Tea",
    price: 49,
    description: "Hot Indian tea",
    category: "Beverage",
    rating: 4.6,
    stock: 40,
    thumbnail:
      "https://www.sharmispassions.com/wp-content/uploads/2012/12/cardamom-tea4-500x500.jpg",
  },
  {
    id: 50,
    title: "Coffee",
    price: 79,
    description: "Fresh brewed coffee",
    category: "Beverage",
    rating: 4.7,
    stock: 35,
    thumbnail:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/flat-white-3402c4f.jpg?quality=90&resize=500,454",
  },
];

export default foodData;
